services:
  # image project
  micro_notification:
    build:
      args:
        user: milena
        uid: 1000
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - micro_notification_queue
    networks:
      - micro_notification_network
      - shared_network

  # nginx
  micro_notification_nginx:
    image: nginx:alpine
    ports:
      - "8585:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - micro_notification_network

  # queue
  micro_notification_queue:
    build:
      args:
        user: milena
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    # command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    networks:
      - micro_notification_network
      - shared_network

networks:
  micro_notification_network:
    driver: bridge
  shared_network:
    external: true
